apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastchat-model-worker.fullname" . }}
  labels:
    {{- include "fastchat-model-worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fastchat-model-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fastchat-model-worker.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fastchat-model-worker.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python3"]
          args:
            - -m
            - fastchat.serve.model_worker
            - --model-names
            - gpt-3.5-turbo,text-davinci-003,text-embedding-ada-002
            - --model-path
            - lmsys/vicuna-7b-v1.5
            - --worker-address
            - http://fastchat-model-worker:21000
            - --controller-address
            - http://fastchat-controller:20000
            - --host
            - 0.0.0.0
            - --port
            - "{{ .Values.service.port }}"
            - --num-gpus
            - "2"
          ports:
            - name: model-worker
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
